# Generated by Django 4.2.6 on 2023-12-11 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsong',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentsong',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='songs.commentsong'),
        ),
        migrations.AddField(
            model_name='commentsong',
            name='song_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_comments', to='songs.song'),
        ),
        migrations.AddField(
            model_name='albumrating',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_ratings', to='songs.album'),
        ),
    ]
