# Generated by Django 4.2.6 on 2023-11-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsong',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='songs.commentsong'),
        ),
    ]
