# Generated by Django 4.2.6 on 2023-11-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_commentsong_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsong',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='songs.commentsong'),
        ),
    ]
