# Generated by Django 4.2.6 on 2023-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Moderator', 'Moderator'), ('Default', 'Default')], default='Default', max_length=20),
        ),
    ]
